# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python_Cl

on:
  push:
    branches: [ "main", "JosueTorresN-patch-1" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment and install dependencies
      run: |
        source ./venv/bin/activate
        python -m pip install --upgrade pip
        pip install pytest

    - name: List files in the repository
      run: |
        ls -R

    - name: Test with pytest
      run: |
        source ./venv/bin/activate
        pytest
